# EDGAR links.
edgar:
  prefix: https://www.sec.gov/Archives/
  url: https://www.sec.gov/Archives/edgar/full-index/

# Logging configuration.
logging:
  level:
    dj:
      mr: DEBUG
    org:
      hibernate:
        SQL: debug
        type: TRACE
        type.descriptor.sql: trace

# Spring data configuration.
spring:
  application:
    name: sec-links
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-data
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: true
        type: trace
        use_sql_comments: true
        default_schema: sec_links
    show-sql: true

# Application host and port details.
server:
  port: 8443

# Spring boot actuator and related end point configuration.
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: env, info, health
  endpoint:
    health:
      show-details: always
    env:
      enabled: true

# Service discovery configuration.
eureka:
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
    home-page-url: /
